site_title: "SciNeW - Scientific News and Insights"
author: "SciNeW Research Team"
description: "A blog-like website showcasing news, insights, publications, and results of the SciNeW research project."
base_url: "https://www.scinew-website.com"
theme: "default"
language: "en"
social_media:
  twitter: "https://twitter.com/scinew"
  facebook: "https://facebook.com/scinew"
  linkedin: "https://linkedin.com/company/scinew"
navigation:
  - title: "Home"
    url: "/index.html"
  - title: "About"
    url: "/about.html"
  - title: "News"
    url: "/news.html"
  - title: "Publications"
    url: "/publications.html"
  - title: "Results"
    url: "/results.html"